### ISSUE TITLE
Consider merge with `savro`

### ISSUE THREAD

**Issue by SemanticBeeng** [wjur/avsc2avdl#1]
Would you consider merging / porting functionality to `savro` project? @wjur 

Here's failing tests based on your examples
https://github.com/SemanticBeeng/savro/blob/0d8a75e53111eb7fb293ff922a4e3b9a7f5c22ba/src/test/scala/ca/dataedu/savro/AvroSchemaToIdlTest.scala#L65-L108

**Comment by wjur** [comment]
Thank you for reporting the issue! Looks interesting, but I need a deeper look and some time before I commit myself for the contribution. I’m going to ping you soon!

**Comment by wjur** [comment]
Once again, thank you for the suggestion, @SemanticBeeng. The fact that someone would like to see a port means to me a lot. It's a clean sign that someone consider my work valuable. However, I unfortunately cannot engage myself into doing the port myself right now and in the nearest future. I went through `savro` repository and could not find any information about the license. The situation would be probably the cleanest if I contribute myself. Anyway, I don't mind if you port the code to `savro`. If you says it's worth it, then why not, right? If you decide to do it yourself, I'll appreciate if you mention me as the original author. Also, I can help you and try to answer any questions if you have any :) What's your opinion, @SemanticBeeng?

**Comment by wjur** [comment]
Closing stale issue
